name: initial_app
description: A new Flutter project.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  android_id: ^0.3.6
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.1
  package_info_plus: ^8.0.0
  pub_semver: ^2.1.4
  shared_preferences: ^2.2.3
  talker: ^4.3.4
  talker_bloc_logger: ^4.3.4
  talker_dio_logger: ^4.3.4
  talker_flutter: ^4.3.4

dev_dependencies:
  build_runner: ^2.4.9

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1


#
flutter:
  uses-material-design: true
